# Generated by Django 5.1.5 on 2025-02-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='endofday',
            unique_together={('symbol', 'date')},
        ),
        migrations.AddIndex(
            model_name='endofday',
            index=models.Index(fields=['symbol', '-date', 'closing_price'], name='idx_symbol_date_price'),
        ),
    ]
