# Generated by Django 5.1.6 on 2025-02-12 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_endofday_idx_symbol_date_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='symbol',
            new_name='symbol_id',
        ),
    ]
