# Generated by Django 5.1.6 on 2025-02-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0004_rename_symbol_stock_symbol_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="description",
        ),
        migrations.DeleteModel(
            name="EndOfDay",
        ),
    ]
