# Generated by Django 5.1.6 on 2025-02-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_symbol_stock_symbol_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofday',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
