# Generated by Django 5.1.6 on 2025-02-14 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_endofday_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endofday',
            old_name='symbol_id',
            new_name='symbol',
        ),
    ]
