# Generated by Django 5.1.6 on 2025-02-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0005_remove_stock_description_delete_endofday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="symbol_id",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
