# Generated by Django 5.1.6 on 2025-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0007_alter_stock_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="exchange",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
