# Generated by Django 5.1.6 on 2025-05-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_leaderboardranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboardranking",
            name="profit",
            field=models.FloatField(default=0),
        ),
    ]
