# Generated by Django 5.1.6 on 2025-04-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpost_board_name_alter_forumcomment_upvotes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='board_name',
        ),
    ]
