# Generated by Django 5.1.6 on 2025-05-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forumpost_board_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='show_comments',
        ),
    ]
