# Generated by Django 5.1.6 on 2025-03-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0004_purchase_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
