# Generated by Django 5.1.6 on 2025-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0005_alter_purchase_date_alter_sale_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
