# Generated by Django 5.1.6 on 2025-03-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0006_alter_purchase_date_alter_sale_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='buying_price',
        ),
        migrations.AddField(
            model_name='share',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
