# Generated by Django 5.1.6 on 2025-03-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_remove_share_buying_price_share_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='quantity_available',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity_purchased',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
