# Generated by Django 5.1.6 on 2025-04-06 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0008_alter_purchase_quantity_available_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=50)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("target_price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wallets.wallet"
                    ),
                ),
            ],
        ),
    ]
