# Generated by Django 5.1.6 on 2025-04-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0009_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="PENDING", max_length=50),
        ),
    ]
