# Generated by Django 5.1.6 on 2025-04-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0011_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="share",
            name="category",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
